### ISSUE TITLE
Runtime error on Windows using own meshes

### ISSUE THREAD

**Issue by lhanes** [nmellado/Super4PCS#12]
Hi Nicolas,

Apologies for originally posting this in the wrong place, I hope this is all in order.

My issue is as follows:
I am using Windows 7, and have downloaded your source code and can compile it in Visual Studio 2015. I can run the hippo registration example from the runme batch file, and it works with no issues.

However, when attempting to register some of my own meshes (in .obj format), it throws a runtime error.

I am attempting to register different sized meshes, some ~75k vertices, some only ~500. The parameters I am using are as follows:
Overlap: 0.5
Delta: 1.0
Max time: 1000
Num Points: 400
Threshold: 1.0
Max Color: 1e9
All others left at default

I have also tried to use some different parameter values but always encounter the same error.

The error I get is as follows:
At ExtractPairs->process->split->erase I get a "vector erase iterator outside range" exception.

![super4pcs_error](https://cloud.githubusercontent.com/assets/19425909/15468254/21494d0a-20db-11e6-8fbc-a00eecedfb3b.png)

I previously sent you 2 of the meshes I am using by email, but I can happily send you the other 2 if needed.

Many thanks for your time,
Laurence

**Comment by nmellado** [comment]
Hi Laurence,

I think I've fixed this bug with commit ef7f054: 

    -  childs.erase(std::remove_if(childs.begin(), childs.end(), [](Node& c)
    -    {return c.rangeLength() == 0; }));
    +  if (!childs.empty()) {
    +	  childs.erase(std::remove_if(childs.begin(), childs.end()-1, [](const Node& c)
    +	  {return c.rangeLength() == 0; }));
    +  }

Your code doesn't seems to be up to date, can you please check you use the last version, either from the repo, or the release [v0.2.1-alpha](https://github.com/nmellado/Super4PCS/releases/tag/v0.2.1-alpha).

**Comment by lhanes** [comment]
Sorry yes, I can verify the issue is fixed as of the latest version.
