### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by JidaHuang** [nmellado/Super4PCS#14]
Hi Dr. Mellado,

I follow the wiki instructions to compiling the code, however, after displaying the error message as below, it stays at the build stage but not moving anymore.
I'm using windows 10, and in Debug mode with x64. And below is the whole error message:

1>------ Build started: Project: Super4pcs, Configuration: Debug x64 ------
1>  super4pcs_test.cc
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(430): error C3646: 'centroid2': unknown override specifier
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(430): error C2838: 'Matrix<double,3,1,0,3,1>': illegal qualified name in member declaration
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(431): error C3646: 'max_angle': unknown override specifier
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(431): error C2377: 'match_4pcs::MatchSuper4PCSImpl::Scalar': redefinition; typedef cannot be overloaded with any other symbol
1>  c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(243): note: see declaration of 'match_4pcs::MatchSuper4PCSImpl::Scalar'
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(432): error C2923: 'Eigen::Matrix': 'match_4pcs::MatchSuper4PCSImpl::Scalar' is not a valid template type argument for parameter '_Scalar'
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(432): error C2143: syntax error: missing ';' before '&'
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(432): error C2838: 'Matrix': illegal qualified name in member declaration
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(434): error C2059: syntax error: ')'
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(434): error C2238: unexpected token(s) preceding ';'
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(262): error C2530: 'match_4pcs::MatchSuper4PCSImpl::centroid1': references must be initialized
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(465): error C2974: 'PairCreationFunctor': invalid template argument for '_Scalar', type expected
1>  c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\paircreationfunctor.h(9): note: see declaration of 'PairCreationFunctor'
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(465): error C2955: 'PairCreationFunctor': use of class template requires template argument list
1>  c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\paircreationfunctor.h(9): note: see declaration of 'PairCreationFunctor'
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(466): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(466): error C2146: syntax error: missing ';' before identifier 'eps'
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(466): error C2065: 'eps': undeclared identifier
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(479): error C2065: 'eps': undeclared identifier
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(482): error C2440: 'initializing': cannot convert from 'Eigen::Matrix<double,3,1,0,3,1>' to 'const Point &'
1>  c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(482): note: Reason: cannot convert from 'Eigen::Matrix<double,3,1,0,3,1>' to 'const Point'
1>  c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(482): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(483): error C2440: 'initializing': cannot convert from 'Eigen::Matrix<double,3,1,0,3,1>' to 'const Point &'
1>  c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(483): note: Reason: cannot convert from 'Eigen::Matrix<double,3,1,0,3,1>' to 'const Point'
1>  c:\users\jida huang\documents\visual studio 2015\projects\super4pcs-0.2.1-alpha\super4pcs\super4pcs.cc(483): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called

**Comment by nmellado** [comment]
Hi,

I'm suspecting an encoding issue.
I've pushed a fix (c7eb6a8), could you please pull and confirm me it is working ?

Cheers

**Comment by JidaHuang** [comment]
Thanks for your quickly response, now it's can be built successfully,  when I run it, it didn't show results window, and display following message:

***** VIDEOINPUT LIBRARY - 0.1995 - TFW07 *****

The thread 0x3ea0 has exited with code -1 (0xffffffff).
The thread 0x3b98 has exited with code -1 (0xffffffff).
The thread 0x3390 has exited with code -1 (0xffffffff).
The program '[4100] Super4pcs.exe' has exited with code -1 (0xffffffff).


How to run it, or do I need to setup something?

**Comment by nmellado** [comment]
You can try to run the file runme.bat (requires x64 binary in release mode).
https://github.com/nmellado/Super4PCS/blob/master/runme.bat

The error code -1 means either :
* invalid input.
* invalid/unknown command line parameter.
