### ISSUE TITLE
too sensitive?

### ISSUE THREAD

**Issue by wpqjbzwm** [nmellado/Super4PCS#15]
hi, @nmellado
I subsampled the hippo ply files, ran two test and got following results. The only differece is the number of kept points, from 90 to 89, but the results changed a lot. 
By the way, when ply format is used, the output ply file is not correct.
I also sent email to you yesterday, please check it. Thank you.

Super4pcs -i h11.ply h22.ply -o 0.7 -d 0.04 -t 1000 -n 90
Super4pcs -i h11.ply h22.ply -o 0.7 -d 0.04 -t 1000 -n 89
@ PAUSE

![clipboard01](https://cloud.githubusercontent.com/assets/19824533/15921365/8149fb16-2e53-11e6-9207-cd588dc9c5d5.jpg)
[subsampled hippos.zip](https://github.com/nmellado/Super4PCS/files/306300/subsampled.hippos.zip)

**Comment by nmellado** [comment]
Hi,

I was working on your data you sent me.
It takes time to reply to all the request, sorry for the 24h delay...

Super4PCS is made to run with much more samples, hundreds or thousands.
As you can see in the log, Super4PCS is using respectively 170 and 85 samples.
In the second case, it is very likely that a good basis cannot be found, leading to the encountered results.
I would recommend to let Super4PCS do the subsampling, by feeding directly the original data.
It runs for clouds of tens of millions of points, without any problem.
Giving too few samples is not a good idea, and makes the algorithm more sensitive to inputs and parameters.


Btw, running the same commands with Linux produce a good result in both cases.
I'll investigate ASAP if their is a platform-specific bug in your case.

> By the way, when ply format is used, the output ply file is not correct.
Can you be more specific here ? Please open another issue if you have trouble with IO, describing why the cloud is not correct, eventually by attaching a file.

**Comment by wpqjbzwm** [comment]
Thanks, nmellado. I'll try more and report here.

**Comment by nmellado** [comment]
IO issue related to #13 and #16.
Closing
