### ISSUE TITLE
Setting LCP delta to <= 0.01 causes crash

### ISSUE THREAD

**Issue by vas85** [nmellado/Super4PCS#2]
Hi

Thanks for the nice library.

When you pass an LCP delta of <= 0.01 the program will crash. This is because the gridDepth in IndexedNormalHealSet (normalHealSet.h) will be very high and Super4PCS::Utils::UnrollIndexLoop will return a very large number (larger than what can fit into 32 bits). This causes several overflow errors and spurious crashes later on.

I think the library should either bail early on if the grid depth exceeds what can be stored with a 32-bit index or just use long / 64-bit indices. 64-bit indices might not work though as it might end up allocating very large amounts of memory.

**Comment by nmellado** [comment]
Hi vas85.

Thanks for flagging the issue and opeming this thread.
I'm unfortunatly quite busy these days, and I might not be able to fix that now.
Fixes are appreciated ;)

Cheers

**Comment by nmellado** [comment]
Small delta values are working (72ff3cf).
