### ISSUE TITLE
Different scale

### ISSUE THREAD

**Issue by qtnext** [nmellado/Super4PCS#25]
I have a point cloud done with photogrammetry or laser scan of a building or an objet and another done with a structured light with a different scsle. Does it  works to find the transformation ( translation rotation and scale ) with your lib ?
Best regards

**Comment by nmellado** [comment]
Hi,

Yes, you can estimate the scale between two clouds, by uncommenting the following line
https://github.com/nmellado/Super4PCS/blob/master/src/super4pcs/super4pcs.cc#L77

This will disable some optimizations in the code, change how the 4-points are compared to the basis, and how the transformation is computed.
Note that the computation time will probably increase a lot.

**Comment by LAICHAO2018** [comment]
I am sorry, the link about the following code is invalid, can you give a new link?
Best Wishes.

**Comment by LAICHAO2018** [comment]
I am sorry, the link about the code is invalid, can you give a new link?
Best Wishes.

**Comment by nmellado** [comment]
Please checkout the OpenGR library : https://github.com/STORM-IRIT/OpenGR
To get the aforementioned feature, you need to define the `MULTISCALE` preprocessor directive.

**Comment by x1597275** [comment]
> I am sorry, the link about the code is invalid, can you give a new link?
> Best Wishes.

hello,could you tell me how do you solve the different scale pointclouds registration use this program?
my QQ-email:962685907@qq.com.
