### ISSUE TITLE
Time check

### ISSUE THREAD

**Issue by mihaimorariu** [nmellado/Super4PCS#26]
Thank you for this great work.

On some point clouds the algorithm takes more time to run than the maximum amount of seconds allowed. I see that the time check is done only inside `Perform_N_steps`, but is there any guarantee that `TryOneBase()` runs within the allowed time? Shouldn't this check be done also within that function and all the others that are called from it?

**Comment by nmellado** [comment]
Hi,
Thanks for the report, you are right, this should be improved.
You can submit a pull request if you wish, or wait until I can find spare time to fix it :)

Cheers
