### ISSUE TITLE
Mac binary

### ISSUE THREAD

**Issue by bxk-sonavex** [nmellado/Super4PCS#28]
Hi Nicolas,

Just saw your v0.2.1-alpha release. I am willing to provide Mac binary.

Xin

**Comment by nmellado** [comment]
Hi Xin,
Thanks, that would help !

cheers

**Comment by bxk-sonavex** [comment]
Hi Nicolas,

Glad to help!  Compiled it on macOS Sierra and ran the 'run-sample.sh'.  Results look good. What is your preferable way to get the binary?

Xin

**Comment by nmellado** [comment]
Sounds good.
Please send me an email directly (see @ in my profile).

Nicolas

**Comment by xinkang** [comment]
Have sent to you a couple of days ago.  Let me know if you did not receive it or have any questions.

Xin
