### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by alexsmartens** [nmellado/Super4PCS#29]
Hi Nicolas,
I have tried to build Super4PCS, but it does not work out. Can you help to fix the problem, please
Thank you!
I'm having the following error:

$ cmake -DCMAKE_BUILD_TYPE=Release -DANN_DIR=/mypathto/ann_1.1.2/ ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found CFITSIO: /usr/lib/x86_64-linux-gnu/libcfitsio.so  
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alex/Downloads/Super4PCS-master/build

$ make
Scanning dependencies of target super4pcs_accel
[  9%] Building CXX object src/super4pcs/accelerators/CMakeFiles/super4pcs_accel.dir/normalHealSet.cpp.o
[ 18%] Linking CXX static library libsuper4pcs_accel.a
[ 18%] Built target super4pcs_accel
Scanning dependencies of target super4pcs_io
[ 27%] Building CXX object src/super4pcs/io/CMakeFiles/super4pcs_io.dir/io.cc.o
In file included from /home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io.cc:2:0:
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h: In function ‘bool readBinary1Body(const string&, unsigned int, unsigned int, unsigned int, unsigned int, bool, bool, std::vector<match_4pcs::Point3D>&, std::vector<cv::Point3_<float> >&, std::vector<tripple>&)’:
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:162:41: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
         /*count = */fread (&c, 1, 1, in);
                                         ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:175:32: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread (v, 4, 6, in);
                                ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:176:51: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread (rgb_buff, sizeof(uchar), 4, in);
                                                   ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:178:32: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread (v, 4, 6, in);
                                ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:179:51: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread (rgb_buff, sizeof(uchar), 3, in);
                                                   ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:181:32: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread (v, 4, 3, in);
                                ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:182:51: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread (rgb_buff, sizeof(uchar), 3, in);
                                                   ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:184:32: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread (v, 4, 3, in);
                                ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:185:51: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread (rgb_buff, sizeof(uchar), 4, in);
                                                   ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:188:52: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread (v, 4, numOfVertexProperties, in);
                                                    ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:237:55: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             /*count = */fread (&polygonSize, 1, 1, in);
                                                       ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:238:44: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             /*count = */fread (f, 4, 3, in);
                                            ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h: In function ‘bool readASCII1Body(const string&, unsigned int, unsigned int, unsigned int, unsigned int, bool, std::vector<match_4pcs::Point3D>&, std::vector<cv::Point3_<float> >&, std::vector<tripple>&)’:
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:269:41: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
         /*count = */fread (&c, 1, 1, in);
                                         ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:283:41: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                 fscanf (in, "%f", &v[j]);
                                         ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:285:48: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                 fscanf (in, "%i", &rgb_buff[j]);
                                                ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:289:41: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                 fscanf (in, "%f", &v[j]);
                                         ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:291:48: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                 fscanf (in, "%i", &rgb_buff[j]);
                                                ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:294:41: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                 fscanf (in, "%f", &v[j]);
                                         ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:296:48: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                 fscanf (in, "%i", &rgb_buff[j]);
                                                ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:299:41: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                 fscanf (in, "%f", &v[j]);
                                         ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:301:48: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                 fscanf (in, "%i", &rgb_buff[j]);
                                                ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:305:41: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
                 fscanf (in, "%f", &v[j]);
                                         ^
/home/alex/Downloads/Super4PCS-master/src/super4pcs/io/io_ply.h:353:86: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
      /*count = */fscanf (in, "%d %d %d %d", &polygonSize, &f[0], &f[1], &f[2]);
                                                                               ^
[ 36%] Linking CXX static library libsuper4pcs_io.a
[ 36%] Built target super4pcs_io
Scanning dependencies of target super4pcs_algo
[ 45%] Building CXX object CMakeFiles/super4pcs_algo.dir/src/super4pcs/4pcs.cc.o
[ 54%] Building CXX object CMakeFiles/super4pcs_algo.dir/src/super4pcs/super4pcs.cc.o
[ 63%] Linking CXX static library libsuper4pcs_algo.a
[ 63%] Built target super4pcs_algo
Scanning dependencies of target chealpix
[ 72%] Building C object 3rdparty/chealpix/CMakeFiles/chealpix.dir/src/chealpix.c.o
[ 81%] Linking C shared library libchealpix.so
[ 81%] Built target chealpix
Scanning dependencies of target Super4PCS
[ 90%] Building CXX object CMakeFiles/Super4PCS.dir/src/super4pcs/super4pcs_test.cc.o
make[2]: *** No rule to make target '/your/path/to/ann_1.1.2/lib/libANN.a', needed by 'Super4PCS'.  Stop.
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/Super4PCS.dir/all' failed
make[1]: *** [CMakeFiles/Super4PCS.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alexsmartens** [comment]
In case somebody has the same issue, you need to download ann http://www.cs.umd.edu/~mount/ANN/ to __yourpath/Super4PCS-master/3rdparty/ann_1.1.2 and build it. 
SOLVED

**Comment by nmellado** [comment]
See compilation instructions here: https://github.com/nmellado/Super4PCS/wiki/Compilation.

**Comment by Adamwgoh** [comment]
Faced the same issue as above. `ann_1.1.2` cloned from the repo could not be built. Follow @alexsmartens provided link and build a new one, then link it via variable in cmake

**Comment by alexsmartens** [comment]
Hi @Adamwgoh,
linux compilation guide gives the following instruction

> mkdir build
> cd build
> cmake -DCMAKE_BUILD_TYPE=Release -DANN_DIR=/your/path/to/ann_1.1.2/ 

note: -DANN_DIR=   **/your/path/to/**  ann_1.1.2/

My problem was that I firstly did not notice that I need to write my path to ann in -DANN_DIR. I just copied the above code without any modification. 
The problem was gone after I specified my path in -DANN_DIR.
Hope it helps

**Comment by Adamwgoh** [comment]
Hi Alex,

oh no, I meant that the `ann` from `/3rdparty` couldn't be build with the listed CMake file, but instead downloading a new one from the homepage and building it works for me. Just to give others a heads up :)

**Comment by nmellado** [comment]
Sorry guys for the mess with libANN.
It should be fixed soon (refactoring is in progress).

**Comment by nmellado** [comment]
Fixed by ad6b25d69fab5f9a4d5baea86da40f1dd54cac11.
