### ISSUE TITLE
problem with building

### ISSUE THREAD

**Issue by manonwo** [nmellado/Super4PCS#3]
I am not able to build the project in CMake because CFITSIO is missing. Shouldn't it be already in the archive as a dependency ? What am i doing wrong ? Then if i add CFITSIO manually i get an error when building it, so the problem is never ending. Can you help ?

Thank you.

**Comment by nmellado** [comment]
Hi,

Could you please detail:
 - your platform (e.g. Linux, Windows),
 - branch used,
 - how you add CFITSIO

Cheers

**Comment by manonwo** [comment]
Hi,

I'm working with windows 7.
I downloaded super4PCS master.
I downloaded CFITSIO library, built it in CMake GUI. Then i add my folder to the built as CFITSIO_INCLUDE_DIR variable (C:/Users/mrcpc/Documents/Manon/review/source codes/12 Super 4PCS/CFITSIO-bld), but in CFITSIO_LIBRARY variable I don't know what is expected. See attached my folder structure, maybe it helps.

Thank you,
Manon



----- Mail original -----
De: "Nicolas Mellado" <notifications@github.com>
À: "nmellado/Super4PCS" <Super4PCS@noreply.github.com>
Cc: "manonwo" <manon.woringer@telecom-bretagne.eu>
Envoyé: Vendredi 4 Décembre 2015 19:07:39
Objet: Re: [Super4PCS] problem with building (#3)

Hi,

Could you please detail:
 - your platform (e.g. Linux, Windows),
 - branch used,
 - how you add CFITSIO

Cheers

---

**Comment by nmellado** [comment]
Hi,

Window builds are not supported on the main branch.
I've done some test to compile on Windows, checkout the branch portWin: https://github.com/nmellado/Super4PCS/tree/portWin 
Note that you need Visual 2015 to compile c++11 code.
You can try to get my .sln file and adapt it to your setup, I had to tune the solution generated by cmake to make it work (I'm not use to Windows builds).

Let me know if you manage to make it work, can be a good opportunity to improve the process for other users. :)

**Comment by nmellado** [comment]
Windows builds are now supported, check wiki.
