### ISSUE TITLE
Tuning parameters

### ISSUE THREAD

**Issue by alexsmartens** [nmellado/Super4PCS#30]
Hi Nicolas,

I'm trying to compare two point clouds of the size ~2M points. They are very similar but with a different scale, orientation and a bit of noise. Initially, I have tried to perform the transformation with ICP algorithms, but they seem to be not suitable in my case. I am wondering if it is possible to do the transformation with Super4PCS. 
I have been trying to test some Super4PCS on my point set. There are my notes: 

1) Changing number of of samples does not make any difference and I get an identity transformation matrix:
```
$ ./Super4PCS -i pt_in.obj pt_target.obj -o 0.75 -d 0.001 -t 1000 -n 4000 -r super4pcs_extreme.obj -m mat_super4pcs_extreme.txt
Use Super4PCS
create tree
create tree ... DONE (2011880 points)
Work with 4006 points
norm_max_dist: 0.001000
Initial LCP: 0.000749
Score: 0.000748877000749                  
0.000748877
(Homogeneous) Transformation from pt_target.obj to pt_in.obj:


                    1.000                     0.000                     0.000                     0.000
                    0.000                     1.000                     0.000                     0.000
                    0.000                     0.000                     1.000                     0.000
                    0.000                     0.000                     0.000                     1.000

Exporting Matrix to mat_super4pcs_extreme.txt...DONE
Exporting Registered geometry to super4pcs_extreme.obj...DONE
```

```
$ ./Super4PCS -i pt_in.obj pt_target.obj -o 0.75 -d 0.001 -n 40000 -r super4pcs_extreme.obj -m mat_super4pcs_extreme.txt
Use Super4PCS
create tree
create tree ... DONE (2011880 points)
Work with 40615 points
norm_max_dist: 0.001000
Initial LCP: 0.000492
Score: 0.000492429.000492                  
0.000492429
(Homogeneous) Transformation from pt_target.obj to pt_in.obj:


                    1.000                     0.000                     0.000                     0.000
                    0.000                     1.000                     0.000                     0.000
                    0.000                     0.000                     1.000                     0.000
                    0.000                     0.000                     0.000                     1.000

Exporting Matrix to mat_super4pcs_extreme.txt...DONE
Exporting Registered geometry to super4pcs_extreme.obj...DONE
```

```
$ ./Super4PCS -i pt_in.obj pt_target.obj -o 1 -d 0.001 -n 40000 -r super4pcs_extreme.obj -m mat_super4pcs_extreme.txt
Use Super4PCS
create tree
create tree ... DONE (2011880 points)
Work with 40615 points
norm_max_dist: 0.001000
Initial LCP: 0.000492
Score: 0.000492429.000492                  
0.000492429
(Homogeneous) Transformation from pt_target.obj to pt_in.obj:


                    1.000                     0.000                     0.000                     0.000
                    0.000                     1.000                     0.000                     0.000
                    0.000                     0.000                     1.000                     0.000
                    0.000                     0.000                     0.000                     1.000

Exporting Matrix to mat_super4pcs_extreme.txt...DONE
Exporting Registered geometry to super4pcs_extreme.obj...DONE
```

2) Changing the order of the input point clouds does make a difference:
```
$ ./Super4PCS -i pt_target.obj pt_in.obj -o 1 -d 0.001 -n 40000 -r super4pcs_extreme.obj -m mat_super4pcs_extreme.txt
Use Super4PCS
create tree
create tree ... DONE (1671110 points)
Work with 40139 points
norm_max_dist: 0.001000
Initial LCP: 0.000349
Score: 0.002142550.002143                  
0.00214255
(Homogeneous) Transformation from pt_in.obj to pt_target.obj:


                    0.143                    -0.989                     0.044                     0.982
                    0.982                     0.136                    -0.132                     0.094
                    0.124                     0.062                     0.990                    -0.944
                    0.000                     0.000                     0.000                     1.000

Exporting Matrix to mat_super4pcs_extreme.txt...DONE
```

3) The transformation from the note # 2 is still not efficient. There is a screenshot of my two point clouds and the transformed one (white):

![image](https://cloud.githubusercontent.com/assets/26261714/24018531/e940d7d4-0a59-11e7-9bad-3252e2d2f29c.png)

What do you think? Would you suggest any parameters to play with?

**Comment by nmellado** [comment]
Hi @alexsmartens ,

Sorry for the late reply.
Just to mention, the scale estimation is an experimental feature.

When the algorithm outputs the identity matrix, it means that no solution has been found.
What are the computation timing for the example you gave ?

Regarding the parameters:
 - overlap: you tried 0.75 and 1. This parameter affects the distance between the pairs of points forming the 4-points basis. If you pick a too large value, the basis will be very large in P (the base cloud°, and potentially goes out of the overlapping region in Q. Do you have an idea of the overlap amount between you two clouds ? You said very similar, does it mean 100% overlap ?
 - delta: you always use 0.001. Are you sure this value is not too small ? delta is the tolerance bound for the registration. Using a too small value (below noise scale or density) means that you try to find a solution that is too perfect to be found.  A good starting point is to set delta at 2 or 3 times the mean density of P. Using a too large value would slow down the algorithm.

I can also have a look at your data.

**Comment by alexsmartens** [comment]
Thank you for your advice. 

For this example I do not have any computational restriction. Should I?

- I would guess that the overlap is around 70-80%
- I do not know my point cloud density. How do you calculate point cloud density?


I experimented with the values of delta and overlap. I basically got three "types" of results

1. Similar to what I have posted earlier:

./Super4PCS -i pt_target.ply pt_in.ply -o 0.5 -d 0.001 -n 40000 -r super4pcs_extreme.obj -m mat_super4pcs_extreme.txt

./Super4PCS -i pt_target.ply pt_in.ply -o 0.1 -d 0.001 -n 40000 -r super4pcs_extreme.obj -m mat_super4pcs_extreme.txt

./Super4PCS -i pt_target.ply pt_in.ply -o 0.1 -d 2 -n 40000 -r delta_super4pcs_extreme.obj -m delta_mat_super4pcs_extreme.txt

./Super4PCS -i pt_target.ply pt_in.ply -o 0.75 -d 1 -n 40000 -r delta_super4pcs_extreme.obj -m delta_mat_super4pcs_extreme.txt

2.  Identity matrix:

./Super4PCS -i pt_target.ply pt_in.ply -o 0.75 -d 2 -n 40000 -r delta_super4pcs_extreme.obj -m delta_mat_super4pcs_extreme.txt

./Super4PCS -i pt_target.ply pt_in.ply -o 0.75 -d 0.5 -n 40000 -r delta_super4pcs_extreme.obj -m delta_mat_super4pcs_extreme.txt

./Super4PCS -i pt_target.ply pt_in.ply -o 0.5 -d 0.5 -n 40000 -r delta_super4pcs_extreme.obj -m delta_mat_super4pcs_extreme.txt

3. Runnung forever (terminated after 24h of running):

./Super4PCS -i pt_target.ply pt_in.ply -o 0.5 -d 0.1 -n 40000 -r delta_super4pcs_extreme.obj -m delta_mat_super4pcs_extreme.txt

./Super4PCS -i pt_target.ply pt_in.ply -o 0.5 -d 0.01 -n 40000 -r delta_super4pcs_extreme.obj -m delta_mat_super4pcs_extreme.txt

_What might you suggest based on this update? Maybe other thoughts?_

I am very curious in transforming my dataset with Super 4-points Congruent Sets algorithm. I have got awesome transformation results of these point clouds with ICP and very good results with CPD (Coherent Drifting Point)  so far. I think Super4PCS is able to produce great results, it is just the matter of parameter tuning. Looking forward to hearing your thoughts on my experiments

**Comment by nmellado** [comment]
> - I would guess that the overlap is around 70-80%

Ok, so you can try `-o 0.7` or `0.8`.

> - I do not know my point cloud density. How do you calculate point cloud density?

You can have a guess with meshlab, bu measuring a distance on your cloud, that you believe to be a good tolerance bound for registration (_I want my two models to be as close as this value)_. 
For instance, with the hippo sample:
![density](https://cloud.githubusercontent.com/assets/6310221/24498067/bc2471e0-153d-11e7-9450-3bb93132af40.gif)
Meshlab measuring tools outputs a distance value around 0.02. As you can see in the `run-example.sh` script, delta is set to half of this value.

Regarding your command line, you've set `-n 40000`. That's really a lot. Using up to 1000 samples is usually enough.
If you want to have a look at the sampled clouds used during the registration process, use options `--sampled1` and `--sampled2` (run with `-h`  for details, or see documentation).

**Comment by alexsmartens** [comment]
@nmellado 

- overlap: ok
- my measurement is around 0.02, so I will be also using - d 0.01

I've played around with the number of samples in the range from 1000 to 8000, the transformation results were not really good.
The last step I decided to try is to check out displaying of sample clouds, and there you go:
![image](https://cloud.githubusercontent.com/assets/26261714/24536033/0f9b8b2c-1595-11e7-9d3a-7afa50ba22be.png)
The sampled point clouds density is drastically different. I tested the similar case with ICP and got similar results. I would guess that the algorithm samples two point clouds with the same amount of point, doesn't it? 
How is it possible to achieve the same number of samples out of two point clouds?

Just in case, here is my log
`
$ ./Super4PCS -i 03BDCR-mesh-sampled-2M.ply pt.ply -o 0.75 -d 0.01 -n 1000 -r super4pcs_extreme.obj -m mat_super4pcs_extreme.txt --sampled1 sampled1.ply --sampled2 sampled2.ply
haveColor
haveColor
Use Super4PCS
create tree
create tree ... DONE (67545 points)
Work with 962 points
norm_max_dist: 0.010000
Initial LCP: 0.006237
Exporting Sampled cloud 1 to sampled1.ply...DONE
Exporting Sampled cloud 2 to sampled2.ply...DONE
Score: 0.0426195
0.0426195
(Homogeneous) Transformation from pt.ply to 03BDCR-mesh-sampled-2M.ply:


                    0.429                    -0.901                    -0.071                     0.083
                   -0.902                    -0.431                     0.026                     0.399
                   -0.054                     0.053                    -0.997                     0.048
                    0.000                     0.000                     0.000                     1.000

Exporting Matrix to mat_super4pcs_extreme.txt...DONE
Exporting Registered geometry to super4pcs_extreme.obj...DONE
`

**Comment by nmellado** [comment]
Just to be sure, did you enable the multiscale exploration ? 
See: https://github.com/nmellado/Super4PCS/issues/25#issuecomment-269807211

**Comment by alexsmartens** [comment]
No, the multiscale exploration was not enabled. 
I enabled it and run the program again. It did not help, I got pretty much the same results

**Comment by nmellado** [comment]
would you mind to share your dataset, so I can evaluate what's going on... (not before next week unfortunately) .

**Comment by alexsmartens** [comment]
@nmellado, I wrote you an email to the address mentioned on your homepage

**Comment by nmellado** [comment]
Hi @alexsmartens ,

I've finally managed to take a look at your data.
The problem seems to come from the scale estimation.

I've manually scaled the target cloud (x2) using meshlab.
Then, the registration goes smoothly by calling

> $ time Super4PCS -i pt_target_scaled.ply pt.ply -d 0.03 -o 0.9 -t 1000 -n 500
> Use Super4PCS
> create tree
> create tree ... DONE (28987 points)
> Work with 509 points
> norm_max_dist: 0.030000
> Initial LCP: 0.172888
> Score: 0.383104 0.383104                 
> 0.383104
> (Homogeneous) Transformation from pt.ply to pt_target_scaled.ply:
>
>
>                     0.985                     0.168                    -0.035                     0.336
>                    -0.169                     0.985                    -0.025                    -0.417
>                     0.031                     0.030                     0.999                    -0.146
>                     0.000                     0.000                     0.000                     1.000
>
> Exporting Registered geometry to output.obj...DONE
>
> real    0m6.209s
> user    0m6.088s
> sys    0m0.116s 

which produces (red is registered pt.ply)
![snapshot01](https://cloud.githubusercontent.com/assets/6310221/24804079/950ffb9e-1bad-11e7-8259-476993afab35.png)

I'll investigate why the multi-scale registration is failing. In the meantime if  you only have models with 100% overlap, you can pre-scale them automatically wrt their bbox size.

Regarding the parameters I've used:
- delta: 0.03, I've used a slightly larger value than yours, in order to cope with noise.  
- n 500: to increase chances to have samples on the parts of the model that help disambiguating with the strong symmetry of the model (top/bottom).

**Comment by alexsmartens** [comment]
Thank you @nmellado .
The scale is my main challenge. It took quite a bit of time to make ICP working properly with respect to scale.

Your current results of model transformation seems to be a bit off so far. 
I have an example of what I would like to have as an output. This is the result of tuned ICP:

![image](https://cloud.githubusercontent.com/assets/26261714/24805658/c06169e2-1b6f-11e7-93b1-629f16275ea7.png)

All the brown elements on the target model have almost exact correspondence to the moving model

Would it be possible to reach similar or better results with Super4PCS?

**Comment by nmellado** [comment]
To be clear, Super4PCS is not aimed for local/fine alignment, but only global/coarse alignment: ICP will most of the time be required to refine the transformation.

**Comment by alexsmartens** [comment]
Far enough. I am still interested. My ICP approach takes about 20min. If I can go through Super4PCS and ICP, and make my computation time to be significantly less, then it would be great. But I definitely cannot go along with manual rescaling

**Comment by nmellado** [comment]
Yes, that's our typical use case.
I'll investigate why the scale estimation fails, and come back to you asap.

Cheers,

**Comment by IanByun** [comment]
@nmellado I am having problems with point cloud scales similarly to those of alexsmartens.
Like liuhang0727, I'd like to know more about "cloud scale" and appropriate parameter setting.

My goal is align pair of overlapping(70~%) Kinect v2 point clouds.
The point clouds are constructed in mm(millimeter) unit with no downscaling.

You mentioned in the paper: "SUPER 4PCS can also directly align multiple Kinect scans (color information ignored) without any volexiation or smoothing."
Can you please share parameter settings when testing those scans?

I have tried:
max_time_seconds INT_MAX
overlapping ratio 0.5 ~ 0.75
sample size 200 ~ 2000
delta 0.1 1.0 5.0 50 etc

Every approach ended up with either
1. Identity matrix
2. Never ending process (more than an hour)
3. bad_alloc and terminate

Any advise or guide would be appreciated.
Best regards

**Comment by alexsmartens** [comment]
@IanByun, you might find [libpointmatcher](https://github.com/ethz-asl/libpointmatcher) and [CPD](https://github.com/gadomski/cpd) useful for point clouds matching and/or scaling.

@IanByun, what are you using for recording Kinect v2 point clouds?

**Comment by IanByun** [comment]
@alexsmartens I am on Windows OS, and using the official MS Kinect v2 driver and **SDK.**
I have managed acquire approximate registration result by downscaling vertex distances by 1000. (that is, I changed distance metric from millimeter to meter)
The strange thing is that 
> metric: meter (1000 millimeter)
> delta: 0.01

somewhat works, but
> metric: millimeter
> delta: 10 

do not work at all (ends up with identity matrix),
although the parameter delta seems to be related to the geometric distance measure,  according to http://nmellado.github.io/Super4PCS/a05043.html.

> For each transformation matrix produced by Super4PCS, we compute the LCP measure by considering a shell around the reference cloud, and count the % of points of the target cloud lying in the shell. **The thickness of the shell** is defined by **the parameter delta**.

I suspect this problem is related to some "magic" numbers hard-coded in the original source.

**Comment by nmellado** [comment]
Thanks @IanByun for the report.
Could you please re-open a dedicated issue here: https://github.com/STORM-IRIT/OpenGR/issues
The thread started by @alexsmartens is not on the exact same topic, and I'm trying to keep the issues as clean as possible.

Scaling 3d models and parameters accordingly should not affect the results.
When creating the new issue, could you share a simple dataset I could use to reproduce your bug ?

> I suspect this problem is related to some "magic" numbers hard-coded in the original source.

There are some indeed, however they are here to help, not to create such behaviors ;)

**Comment by nmellado** [comment]
Hi @liuhang0727,
Sorry we missed your post.

In this context the scale means the size of the model, in term of scene units.
Imagine you want to register a box of diagonal size = 2, to a box of diagonal size = 1.
In this specific case, you look for a scale factor of 0.5 between the first and the second model.

This is what @alexsmartens is working on, ie. finding the rotation + translation **+ scale** between two models.

**Comment by utsavrai** [comment]
Hi Nicolas,

I am trying to fit a point cloud which is cropped from the target point cloud. The cropped point cloud is transformed in x, y and z direction in order to check if Super4PCS is able to fit it back to its place in target point cloud. Using Super4PCS I am not able to do it so, it is giving some transitional shift.

Transformation matrix used to transform cropped point cloud-
       1        0        0      4
       0        1        0      3
       0        0        1      2
       0        0        0      1


I tried changing parameters, also tried re-scaling the point cloud and since the cropped point cloud is a part of target point cloud so it overlaps 100%.

I used - 
 ./Super4PCS -i ~/utsav/dataset/RealSense/ply/target.ply ~/utsav/dataset/RealSense/ply/cropped_transformed.ply -o 1 -d 0.01 -t 10000 -n 2000 -r super4pcs_fast_test.obj -m mat_super4pcs_fast_test.txt


OUTPUT- 
haveColor
(PLY) ignoring unknown element camera
haveColor
Starting registration
norm_max_dist: 0.01
Initial LCP: 0.0085
Score: 0.0085t: 0.008500                  
(Homogeneous) Transformation from /home/ankita/utsav/dataset/RealSense/ply/cropped_transformed.ply to /home/ankita/utsav/dataset/RealSense/ply/target.ply: 
       1        0        0 -3.48968
       0        1        0 -3.01475
       0        0        1 -1.70298
       0        0        0        1
Exporting Matrix to mat_super4pcs_fast_test.txt...
Export DONE
Exporting Registered geometry to super4pcs_       1        0        0 -3.48968
       0        1        0 -3.01475
       0        0        1 -1.70298
       0        0        0        1fast_test.obj...
Export DONE


TARGET POINT CLOUD (INPUT 1)
![target](https://user-images.githubusercontent.com/25121619/52463811-70defd80-2b9e-11e9-8363-a72208a906ba.png)

CROPPED POINT CLOUD (INPUT 2)
![cropped](https://user-images.githubusercontent.com/25121619/52463908-c915ff80-2b9e-11e9-834e-bb52cb806585.png)

BEFORE USING Super4PCS
![screenshot from 2019-02-08 13-39-19](https://user-images.githubusercontent.com/25121619/52466109-2dd55800-2ba7-11e9-8e77-5167ca9750a6.png)

AFTER USING Super4PCS
![retransformed](https://user-images.githubusercontent.com/25121619/52466302-ea2f1e00-2ba7-11e9-8353-b9fc126f0943.png)

The correct output of Super4PCS should be
       1        0        0      -4
       0        1        0      -3
       0        0        1      -2
       0        0        0        1

I am using the point cloud captured from Intel RealSense SR300 using RealSense Wrapper for ROS.
Please help me with this.
