### ISSUE TITLE
Create tree only found 8 points

### ISSUE THREAD

**Issue by xinkang** [nmellado/Super4PCS#33]
I am trying to register one point cloud obtained from data to another obtained from CAD model.  The data and the model point cloud has 41373 and 7000 points, respectively.  I used PLY ASCII format and double checked the inputs.  However, I obtained the following strange error--the create tree only took 8 pints.  Did I missed something?

```
./Super4PCS -i ptsMarker.ply ptsData.ply
Use Super4PCS
create tree
create tree ... DONE (8 points)
Work with 8 points
norm_max_dist: 5.000000
Initial LCP: 1.000000
[Error]: [IndexedNormalHealSet] Invalid configuration (depth=-2, size=0)
Aborting with code -2 ...
```

FYI, the two point clouds are in their own coordinate systems.  Would this a problem?  If so, what do you suggest to do?

Thanks,
Xin

**Comment by nmellado** [comment]
Hi @xinkang ,

It might be caused by improper parameters. 
Depending on the scale of your dataset, the default parameters can be totally off.

You may want to have a look at the [wiki](http://github.com/nmellado/Super4PCS/wiki/Usage) and issue #30 for more details.

**Comment by bxk-sonavex** [comment]
Hi @nmellado,

Have read the wiki page and the referred issue but did not figure out which parameter(s) influences the creation of tree (kdtree I guess).  Could you point one or two parameters I should start to explore?  Thanks!

**Comment by nmellado** [comment]
Hi,
You need to set a value for delta, the overlap and the number of points, as described in the wiki.
Cheers,
