### ISSUE TITLE
compiling issue: cannot find -lANN_DIR-NOTFOUND/lib/libANN.a

### ISSUE THREAD

**Issue by tanajikamble13** [nmellado/Super4PCS#34]
make gives error:
/usr/bin/ld: cannot find -lANN_DIR-NOTFOUND/lib/libANN.a
i have installed library using command **sudo apt-get install libann-dev**
Let me know how to overcome the error

**Comment by nmellado** [comment]
Hi,
As stated in the compilation instruction, you need to call cmake with the path to libANN.
Package installation is not supported, please download libann and compile it on your system.

Please see this as temporary fix, I'm currently working at removing this dependency.

**Comment by nmellado** [comment]
Fixed by ad6b25d69fab5f9a4d5baea86da40f1dd54cac11
