### ISSUE TITLE
Fix compile error on macOS

### ISSUE THREAD

**Issue by xinkang** [nmellado/Super4PCS#37]
Compile error in `match4pcsBase.cc`. 

At lines 130 and 131, use `std::abs`.  
From line 871 to 876, use `std::cout` and `std::endl`.

Tried to do a PR, but obviously I do not have permission.

**Comment by nmellado** [comment]
Hi @xinkang .

Thanks for the report.
I've fixed this in the `travis-setup` branch (see PR #38).
It should be merged with `master` soon.

If you want to contribute, please let me know, I can add you as contributor.
Alternatively, you may also want fork the project and propose PR directly from you forked repository, as described here: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by nmellado** [comment]
Fixed by commit 97fc8e1.
Please re-open if any trouble
