### ISSUE TITLE
When will the wrappers of PCL be released？

### ISSUE THREAD

**Issue by zfrxiaxia** [nmellado/Super4PCS#41]
When will the wrappers of PCL be released？

**Comment by nmellado** [comment]
Hi,

This wrapper is part of my mid-term roadmap.
I don't have a clear deadline for this, but hopefully it will be done by the end of the year.

Of course if many people request it I can try to speed this up.

**Comment by xinkang** [comment]
I love this idea.  It will be a great feature and probably a good way to get the algorithm exposed to a larger population.

**Comment by zfrxiaxia** [comment]
Thanks for your work

**Comment by nmellado** [comment]
Here you go ;)

**Comment by nmellado** [comment]
@zfrxiaxia @xinkang ,
A first version of the PCLWrapper is available in branch v1.1.3RC, if you want to test it....

**Comment by zfrxiaxia** [comment]
#45 I got this from Super4PCS-PCLWrapper
////////////////////////////////////////////////////////////////////////////////////
./Super4PCS-PCLWrapper hippo1.obj hippo2.obj 
> Loading point clouds...
Failed to find match for field 'curvature'.
Failed to find match for field 'curvature'.
> Starting alignment...
norm_max_dist: 5
Initial LCP: 1
Segmentation fault (core dumped)
////////////////////////////////////////////////////////////////////////////////////

**Comment by nmellado** [comment]
@zfrxiaxia , thanks for testing.

Sorry, I forgot to give you proper run instructions.
Segfault is now fixed 0f43688.

To test the wrapper, please run:
```../bin/Super4PCS-PCLWrapper ../assets/hippo1.obj ../assets/hippo2.obj -o 0.7 -d 0.01 -t 1000 -n 200```
(path to binary and assets must be adapted)

**Comment by nmellado** [comment]
Done with new release v1.1.3.
Closing
