### ISSUE TITLE
undefined reference to `cv::imread(std::string const&, int)'

### ISSUE THREAD

**Issue by chuong** [nmellado/Super4PCS#47]
Thanks for the great work. I tried to compile Super4PCS on Ubuntu 16.04 with system's OpenCV 2.4.9 installation. Although OpenCV link is optional but it would be great if this works.  Below is output:

$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The CXX compiler identification is GNU 4.9.3
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Eigen3 root path: /home/chuong/workspace/Super4PCS/3rdparty/Eigen
-- The C compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- [Deps] Use OpenCV for image loading
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chuong/workspace/Super4PCS/build

$ make install
Scanning dependencies of target super4pcs_io
[ 12%] Building CXX object src/super4pcs/io/CMakeFiles/super4pcs_io.dir/io.cc.o
[ 25%] Linking CXX static library libsuper4pcs_io.a
[ 25%] Built target super4pcs_io
Scanning dependencies of target super4pcs_algo
[ 37%] Building CXX object src/super4pcs/algorithms/CMakeFiles/super4pcs_algo.dir/match4pcsBase.cc.o
[ 50%] Building CXX object src/super4pcs/algorithms/CMakeFiles/super4pcs_algo.dir/4pcs.cc.o
[ 62%] Building CXX object src/super4pcs/algorithms/CMakeFiles/super4pcs_algo.dir/super4pcs.cc.o
[ 75%] Linking CXX static library libsuper4pcs_algo.a
[ 75%] Built target super4pcs_algo
Scanning dependencies of target Super4PCS
[ 87%] Building CXX object demos/Super4PCS/CMakeFiles/Super4PCS.dir/super4pcs_test.cc.o
[100%] Linking CXX executable Super4PCS
../../src/super4pcs/io/libsuper4pcs_io.a(io.cc.o): In function `IOManager::ReadObj(char const*, std::vector<GlobalRegistration::Point3D, std::allocator<GlobalRegistration::Point3D> >&, std::vector<Eigen::Matrix<float, 2, 2, 0, 2, 2>, std::allocator<Eigen::Matrix<float, 2, 2, 0, 2, 2> > >&, std::vector<Eigen::Matrix<float, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<float, 3, 1, 0, 3, 1> > >&, std::vector<tripple, std::allocator<tripple> >&, std::vector<std::string, std::allocator<std::string> >&)':
io.cc:(.text+0x6b9a): undefined reference to `cv::imread(std::string const&, int)'
collect2: error: ld returned 1 exit status
demos/Super4PCS/CMakeFiles/Super4PCS.dir/build.make:99: recipe for target 'demos/Super4PCS/Super4PCS' failed
make[2]: *** [demos/Super4PCS/Super4PCS] Error 1
CMakeFiles/Makefile2:1498: recipe for target 'demos/Super4PCS/CMakeFiles/Super4PCS.dir/all' failed
make[1]: *** [demos/Super4PCS/CMakeFiles/Super4PCS.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nmellado** [comment]
Hi @chuong ,
Thanks for the report.
Could you please confirm me c9969305c12fb02c17981047688fa6180adc764d is fixing your problem ?

Cheers,

**Comment by zfrxiaxia** [comment]
i got this when i use opencv3.1, try opencv2.4.9

**Comment by nmellado** [comment]
Thanks @zfrxiaxia for your comment.
Indeed it was an issue with Opencv 3.x, which implements `imread` in the package `imgcodec`, which is not existing in previous Opencv versions.

Commit c9969305c12fb02c17981047688fa6180adc764d is fixing that by detecting the OpenCV version and loading the correct packages.

**Comment by chuong** [comment]
Hi @nmellado. Thanks for the commit, however it doesn't fix the error yet

`$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The CXX compiler identification is GNU 4.9.3
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Eigen3 root path: /home/chuong/workspace/Super4PCS/3rdparty/Eigen
-- The C compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- [Deps] Use OpenCV 2.4.9.1 for image loading
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chuong/workspace/Super4PCS/build

$ make install
Scanning dependencies of target super4pcs_io
[ 12%] Building CXX object src/super4pcs/io/CMakeFiles/super4pcs_io.dir/io.cc.o
[ 25%] Linking CXX static library libsuper4pcs_io.a
[ 25%] Built target super4pcs_io
Scanning dependencies of target super4pcs_algo
[ 37%] Building CXX object src/super4pcs/algorithms/CMakeFiles/super4pcs_algo.dir/match4pcsBase.cc.o
[ 50%] Building CXX object src/super4pcs/algorithms/CMakeFiles/super4pcs_algo.dir/4pcs.cc.o
[ 62%] Building CXX object src/super4pcs/algorithms/CMakeFiles/super4pcs_algo.dir/super4pcs.cc.o
[ 75%] Linking CXX static library libsuper4pcs_algo.a
[ 75%] Built target super4pcs_algo
Scanning dependencies of target Super4PCS
[ 87%] Building CXX object demos/Super4PCS/CMakeFiles/Super4PCS.dir/super4pcs_test.cc.o
[100%] Linking CXX executable Super4PCS
../../src/super4pcs/io/libsuper4pcs_io.a(io.cc.o): In function `IOManager::ReadObj(char const*, std::vector<GlobalRegistration::Point3D, std::allocator<GlobalRegistration::Point3D> >&, std::vector<Eigen::Matrix<float, 2, 2, 0, 2, 2>, std::allocator<Eigen::Matrix<float, 2, 2, 0, 2, 2> > >&, std::vector<Eigen::Matrix<float, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<float, 3, 1, 0, 3, 1> > >&, std::vector<tripple, std::allocator<tripple> >&, std::vector<std::string, std::allocator<std::string> >&)':
io.cc:(.text+0x6b9a): undefined reference to `cv::imread(std::string const&, int)'
collect2: error: ld returned 1 exit status
demos/Super4PCS/CMakeFiles/Super4PCS.dir/build.make:98: recipe for target 'demos/Super4PCS/Super4PCS' failed
make[2]: *** [demos/Super4PCS/Super4PCS] Error 1
CMakeFiles/Makefile2:1498: recipe for target 'demos/Super4PCS/CMakeFiles/Super4PCS.dir/all' failed
make[1]: *** [demos/Super4PCS/CMakeFiles/Super4PCS.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by nmellado** [comment]
Ok, should be fixed now.
I've done some over-engineered code with OpenCV, sorry guys.
