### ISSUE TITLE
Access to MVS datasets

### ISSUE THREAD

**Issue by Vodake97** [nmellado/Super4PCS#52]
Dear all
  Sorry to bother you in this way . I am interested in your test data two point-clouds of the Cathedral of Pisa one acquired using LI- DAR and the other using Multi-View Stereo (MVS) recon- struction. I download your  dataset but i can find it. And I search the internet but i can not find it.
 Is it your own data or some public datasets.How can I get it ?
   Please.

**Comment by nmellado** [comment]
Hi @Vodake97,

The dataset is aivailabe at: http://www.irit.fr/~Nicolas.Mellado/datasets

Cheers

**Comment by Vodake97** [comment]
Thank you so much for replying this issue . But is this a reconstruct data? How can I get the original data?

**Comment by nmellado** [comment]
Hi @Vodake97,

I've added the source images here: https://www.irit.fr/recherches/VORTEX/MelladoNicolas/3d-multimodal-point-clouds-and-meshes/.

++

**Comment by xuzr** [comment]
Thank you so much for doing this
