### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by weiquanmao** [nmellado/Super4PCS#53]
There might be a code error at [super4pcs.cc#L209](https://github.com/nmellado/Super4PCS/blob/master/src/super4pcs/algorithms/super4pcs.cc),

```cpp
#ifdef MULTISCALE
  BruteForceFunctor
  <PairCreationFunctor<Scalar>::Point, 3, Scalar> interFunctor;
#else
...
```

which I think should be 

```cpp
#ifdef MULTISCALE
  BruteForceFunctor
  <PairCreationFunctor<Scalar>::Primitive, PairCreationFunctor<Scalar>::Point, 3, Scalar> interFunctor;
#else
...
```

By the way, does it work to use `MULTISCALE` for aligning point clouds with scale variation?

**Comment by nmellado** [comment]
Thanks for the report.

Yes, setting `MULTISCALE` adds relative scale factor estimation. 
This option is not documented as the current implementation has not been carefully tested, and is obviously time consuming.
