### ISSUE TITLE
Base selection problem

### ISSUE THREAD

**Issue by ivivyfei** [nmellado/Super4PCS#58]
hello！
1. In RANSAC，the iteration times seriously effects the results accuracy.   I set overlap parameter as 0.5 and 0.7，and I get same results. After about 15 times，the best base is obtained. I wonder how the overlap parameter effects the results? 
2. How to set the random seed to get better base? different seed may lead to different base.
3. In terms of my data case, the two point cloud need to align in real time.  Is this Super4PCS a suitable solution?

**Comment by nmellado** [comment]
Hi,

> 1. In RANSAC，the iteration times seriously effects the results accuracy. I set overlap parameter as 0.5 and 0.7，and I get same results. After about 15 times，the best base is obtained. I wonder how the overlap parameter effects the results?

First of all, the Super4PCS app has a parameter to stop the computation after `n` seconds.  Setting this time too low might lead to unwanted partial exploration of the set and inconsistent results (default is 10 seconds).

There is an explanation on how the overlap affects the computation in the documentation (http://nmellado.github.io/Super4PCS/a05043.html)

>2. How to set the random seed to get better base? different seed may lead to different base.

Regarding the random seed, by default it is set as `std::mt19937::default_seed`. There is no mechanism in the CLI to change it, however you could modify it in the code, for instance by adding in `super4pcs_test.cc`, at line 86:
```c++
options.randomSeed = /*YOUR_SEED*/;
```
It's true that changing the seed might affect the base selection (see `Match4PCSBase::SelectRandomTriangle`).
> 3. In terms of my data case, the two point cloud need to align in real time. Is this Super4PCS a suitable solution?

Hum... it depends :) :
 - What do you mean by real time ? 25fps, 1fps (interactive), something else ?
 - What kind of motion are you trying to solve ? Do you really need global registration, or is ICP enough ?
 - In the same spirit, what do you know about the overlap between consecutive frames ?
 - Is the incoming geometry (and thus expected transformation) temporally coherent ? 
 - Do you have any knowledge about the input geometry and represented shapes ?

Answers to this questions could help to define prior to specialize and speed up the algorithm. Of course this would some dedicated development.

**Comment by ivivyfei** [comment]
Thanks very much! I've been looking forward your reply.
I try to get the relative pose for a moving spaceborne object like an artificial satellite using LiDAR, so 1fps is enough. And the reference 3D model of the target is known.  Global registration is nesscary in the first time to get a rough intial pose. After that ICP is used to tracking the target. My questions are:
1.  Is super4PCS suitable for my case? 1 fps is enough. And building a bases libarary offline instead of randomly selecting bases, may be a way to save the time cost?
2.  Super4PCS may fail since the symmetry of the target.

**Comment by nmellado** [comment]
As far as in understand, the main challenge in your case, will be to handle the potentially small size of the spaceborne, in comparison with the whole LIDAR (sky ?) point-cloud.
If the size of the spaceborne is too small, it will lead to large congruent set and many configurations to tests, which takes time.

It's hard to say without seeing the data, but it would probably help to filter the congruent set w.r.t. point-wise properties (if you have some: colors, reflectivity), or to first detect potential matching points to prune the LIDAR scan.
What the size of the LIDAR scan btw ?
