### ISSUE TITLE
cmake is not able to find meshlab

### ISSUE THREAD

**Issue by shomedas** [nmellado/Super4PCS#62]
i have installed meshlab via synaptic. However ccmake is not able to find meshlab.

Do I have to install meshlab from source?

**Comment by nmellado** [comment]
Yes indeed, you need to install meshlab from source to compile the plugin and get it working.

`FindMeshlab.cmake` looks for meshlab in `MESHLAB_SRC_DIR`, so you may run `cmake .. -DMESHLAB_SRC_DIR=/path/to/meshlab/src`.


---
The Super4PCS library is not maintained anymore

It is replaced by the fork OpenGR: https://github.com/STORM-IRIT/OpenGR

Except critical bug fix, no changes will be added to this repo. Please request support on OpenGR issue tracker.
