### ISSUE TITLE
Got wrong results by using this software with your datasets

### ISSUE THREAD

**Issue by leoshaolong** [nmellado/Super4PCS#63]
When I open run-example.bat,I got the following answers:

**Comment by leoshaolong** [comment]
成功: 指定的值已得到保存。

C:\Users\ABC\Desktop\4PCS\scripts>..\bin\Super4pcs -i ..\assets\hippo1.obj ..\assets\hippo2.obj -o 0.7 -d 0.01 -t 1000 -n 200 -r super4pcs_fast.obj -m mat_super4pcs_fast.txt
Use Super4PCS
norm_max_dist: 0.01
Initial LCP: 0
[Unknown Error]: Aborting with code -3 ...

C:\Users\ABC\Desktop\4PCS\scripts>..\bin\Super4pcs -i ..\assets\hippo1.obj ..\assets\hippo2.obj -o 0.7 -d 0.01 -t 1000 -n 200 -r      4pcs_fast.obj -m      mat_4pcs_fast.txt -x
Use old 4PCS
norm_max_dist: 0.01
Initial LCP: 0
Score: 0% best: 0.000000
(Homogeneous) Transformation from ..\assets\hippo2.obj to ..\assets\hippo1.obj:
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
Exporting Matrix to mat_4pcs_fast.txt...
Export DONE
Exporting Registered geometry to 4pcs_fast.obj...
Export DONE

**Comment by nmellado** [comment]
Hi,
I guess you are on windows. How did you get the binaries ? If you compiled from source, could you tell me the commit number ? Or the version number if you get precompiled libraries.
Also, the Super4PCS library is not maintained anymore (except bug-fixes), please try with OpenGR, it might fix your bug.

**Comment by haixingxin** [comment]
D:\super4pcs\scripts>..\bin\Super4pcs -i ..\assets\hippo1.obj ..\assets\hippo2.obj -o 0.7 -d 0.01 -t 1000 -n 200 -r super4pcs_fast.obj -m mat_super4pcs_fast.txt
Use Super4PCS
norm_max_dist: 0.01
Initial LCP: 0.75
Score: 0.97est: 0.970000
(Homogeneous) Transformation from ..\assets\hippo2.obj to ..\assets\hippo1.obj:
   0.907348   -0.419179  -0.0317605   -0.478284
   0.419406    0.907799 0.000539497   -0.108833
  0.0286062    -0.01381    0.999495 -0.00517923
          0           0           0           1
Exporting Matrix to mat_super4pcs_fast.txt...
Export DONE
Exporting Registered geometry to super4pcs_fast.obj...
Export DONE

D:\super4pcs\scripts>..\bin\Super4pcs -i ..\assets\hippo1.obj ..\assets\hippo2.obj -o 0.7 -d 0.01 -t 1000 -n 200 -r      4pcs_fast.obj -m      mat_4pcs_fast.txt -x
Use old 4PCS
norm_max_dist: 0.01
Initial LCP: 0.75
done: 0% best: 0.750000
