### ISSUE TITLE
Using this library in my own project

### ISSUE THREAD

**Issue by ivivyfei** [nmellado/Super4PCS#64]
Hi，
I want to use this library in my own project！My project is developed on Visual Studio 2010.
Sadly，I get many syntax errors after I indlude the head file.
Is my VS version  too old for that?

**Comment by nmellado** [comment]
Hi,
As detailed here: http://nmellado.github.io/Super4PCS/a05034.html
The Super4PCS library requires C++11 support, which is not the case of Visual Studio 2010.
You need a more recent version ; I use VS2017 Community Edition with CMake support.

Also, the Super4PCS library is not maintained anymore, you may want to consider its fork OpenGR: https://github.com/STORM-IRIT/OpenGR

**Comment by ivivyfei** [comment]
ok！thank u very much！
