### ISSUE TITLE
Could not align well

### ISSUE THREAD

**Issue by meakcey** [nmellado/Super4PCS#65]
I could not get proper alignment with the attached clouds.
I have tried so many parameters but no luck.
Can you pls advice some parameter or way of thinking to align at least these two.

My current parameters are
overlap: 0.6
delta: 5.0
n_points: 150
max_time_seconds: 30

[CloudsObj.zip](https://github.com/nmellado/Super4PCS/files/2739978/CloudsObj.zip)

**Comment by nmellado** [comment]
Moving this issue to OpenGR: https://github.com/STORM-IRIT/OpenGR/issues/18
