### ISSUE TITLE
CMake compile error

### ISSUE THREAD

**Issue by Timbersaw-wangzw** [nmellado/Super4PCS#68]
I encounteded a error about CMake complie.The error info is:"Super4PCS-master\CMakeLists.txt:146 (string):string sub-command SUBSTRING requires four arguments" Can you tell me how to fix it?

**Comment by nmellado** [comment]
Super 4PCS is not maintained anymore.
It has been replaced by OpenGR, please checkout https://github.com/STORM-IRIT/OpenGR.
