### ISSUE TITLE
Different result of your video demonstration

### ISSUE THREAD

**Issue by sebastien247** [nmellado/Super4PCS#70]
Hi,
First, thanks for your work.
I implemented OpenGR with the VTK render to see the result. Unfortunately, I didn't obtain the same result as this video: https://www.youtube.com/watch?v=TgHrotscPCA whether on Super4PCS or 4PCS.

this is options applied for Super4PCS and 4PCS (same options in run-example.bat):
```
    OptionType options;
    options.configureOverlap( 0.7 );
    options.delta = 0.01;
    options.sample_size = 200;
    options.max_time_seconds = 1000;
```

It's the result matrix:

```
  | [0] | 0.78860002756118774 | double
  | [1] | 0.23901370167732239 | double
  | [2] | 0.56655317544937134 | double
  | [3] | 0.00000000000000000 | double
  | [4] | -0.10672703385353088 | double
  | [5] | 0.96058332920074463 | double
  | [6] | -0.25668844580650330 | double
  | [7] | 0.00000000000000000 | double
  | [8] | -0.60557353496551514 | double
  | [9] | 0.14195793867111206 | double
  | [10] | 0.78302532434463501 | double
  | [11] | 0.00000000000000000 | double
  | [12] | -0.13029700517654419 | double
  | [13] | 0.024866815656423569 | double
  | [14] | -0.025774050503969193 | double
  | [15] | 1.0000000000000000 | double
```

![image](https://user-images.githubusercontent.com/2801027/97293568-252a2700-184d-11eb-9e8b-42ae996f7174.png)

Thanks for your help

Sébastien

**Comment by nmellado** [comment]
Hi,
Super4PCS library is now deprecated and superseded by https://github.com/STORM-IRIT/OpenGR
Could you please retry your experiment on OpenGR `master` branch, open a dedicated issue there, share the dataset used, and detail your compiler and operating system.
Cheers
Nicolas
