### ISSUE TITLE
hello, Is there someone know how to use the 4psc with pcl?

### ISSUE THREAD

**Issue by tiexuedanxin** [nmellado/Super4PCS#71]

**Comment by nmellado** [comment]
Hi,

What do you want to know exactly ?
The PCL wrapper is compiled by calling `make Super4PCS-PCLWrapper`.

**Comment by tiexuedanxin** [comment]
> Hi,
> 
> What do you want to know exactly ?
> The PCL wrapper is compiled by calling `make Super4PCS-PCLWrapper`.

hello, I want to use the Super4PCS in 3d reconstruction to align point cloud which captureed from different view of a same object, bucause i need to reconstruct a lot of objects, i don't know whether Super4PCS can work well, and do i need to set different parameter for different object(this is very trouble)?

**Comment by nmellado** [comment]
Guidelines to set parameters are given here: http://nmellado.github.io/Super4PCS/a05043.html

Super4PCS is useful if you have strong motion between the different views. 
If you want a concrete example, please share two point-clouds so I can give you examples of working parameters.

**Comment by tiexuedanxin** [comment]
> Guidelines to set parameters are given here: http://nmellado.github.io/Super4PCS/a05043.html
> 
> Super4PCS is useful if you have strong motion between the different views.
> If you want a concrete example, please share two point-clouds so I can give you examples of working parame





> Guidelines to set parameters are given here: http://nmellado.github.io/Super4PCS/a05043.html
> 
> Super4PCS is useful if you have strong motion between the different views.
> If you want a concrete example, please share two point-clouds so I can give you examples of working parameters.

could you give me you email address, i will share my data with you, very than you.

**Comment by nmellado** [comment]
You can find it on my GitHub profile page.

**Comment by tiexuedanxin** [comment]
> You can find it on my GitHub profile page.

I have sent my data to you.

**Comment by tiexuedanxin** [comment]
> You can find it on my GitHub profile page.

hello, have you receive my email?

**Comment by nmellado** [comment]
Hi, no I didn’t. Maybe you exceed the max size allowed ?

**Comment by tiexuedanxin** [comment]
> Hi, no I didn’t. Maybe you exceed the max size allowed ?

hello, have you receive my email? I have send again.

**Comment by nmellado** [comment]
Hello, yes I got it this time, I’ll try to have a look by the end of the week.

**Comment by tiexuedanxin** [comment]
> Hello, yes I got it this time, I’ll try to have a look by the end of the week.

hello, have you solve the problem?

**Comment by tiexuedanxin** [comment]
> Hello, yes I got it this time, I’ll try to have a look by the end of the week.

hello, Have you solve the problem?

**Comment by nmellado** [comment]
Hello,
Sorry I have a big deadline for tomorrow, after that I'll have a look at your data.

**Comment by nmellado** [comment]
I took a look at your data and managed to register it.
Are you fine if are post here some screenshot showing the data and explaining how I did ?

**Comment by tiexuedanxin** [comment]
> I took a look at your data and managed to register it.
> Are you fine if are post here some screenshot showing the data and explaining how I did ?
ok, thanks for help me, you can post screenshot here. Could you add some refine algorithm like ICP to get a perfect result.

**Comment by tiexuedanxin** [comment]
> I took a look at your data and managed to register it.
> Are you fine if are post here some screenshot showing the data and explaining how I did ?

The problem is that I need to  register a lot of pint cloud, and if the 4psc can register all 
 the data ( I am for sure that the point cloud need to register all are overlaped with each other). Besides I don't want to tune parameter for every time when register different point cloud, if you have some ideas to solve the problem.

**Comment by nmellado** [comment]
I added the tutorial on OpenGR repository (see link below).

Regarding your use case:
 - if you acquire objects of similar size using the same method, you can keep the same parameter values. In case you got more complex objects, you can increase the number of samples (e.g., 500) so increase chances to get good registration results in all cases.
 - regarding ICP: we don't have that in OpenGR. But, a good solution is to use OpenGR with cgal, and then you get ICP for free (implementation by libpointmatcher). More details on this:  https://doc.cgal.org/latest/Point_set_processing_3/index.html#title17

**Comment by tiexuedanxin** [comment]
> I added the tutorial on OpenGR repository (see link below).
> 
> Regarding your use case:
> 
> * if you acquire objects of similar size using the same method, you can keep the same parameter values. In case you got more complex objects, you can increase the number of samples (e.g., 500) so increase chances to get good registration results in all cases.
> * regarding ICP: we don't have that in OpenGR. But, a good solution is to use OpenGR with cgal, and then you get ICP for free (implementation by libpointmatcher). More details on this:  https://doc.cgal.org/latest/Point_set_processing_3/index.html#title17

hello, have you  register my data successfully, Is there some register result screenshot ? the right way for me is to use OpenGR with cgal as you link says?

**Comment by nmellado** [comment]
For screenshot and description of the method see: https://github.com/STORM-IRIT/OpenGR/issues/74

OpenGR+CGAL allows you to chain OpenGR algorithms with ICP very easily. Alternatively, you can also chain OpenGR and libpointmatcher yourself.

**Comment by tiexuedanxin** [comment]
> For screenshot and description of the method see: [STORM-IRIT#74](https://github.com/STORM-IRIT/OpenGR/issues/74)
> 
> OpenGR+CGAL allows you to chain OpenGR algorithms with ICP very easily. Alternatively, you can also chain OpenGR and libpointmatcher yourself.

hello, the data I have sent you also has a chair back, Is the chair back register successfully, I find register the chair back very difficulty.

**Comment by nmellado** [comment]
I got good alignement with the same parameters, except the number of points that I had to increase to 500, as suggested in the tutorial.

**Comment by tiexuedanxin** [comment]
> I got good alignement with the same parameters, except the number of points that I had to increase to 500, as suggested in the tutorial.

very thank you. I come across to see that there is Poisson Surface Reconstruction in the CGAL link, because i also need to reconstruct the surface with color, if I can get a point cloud with color, is there some ways to  reconstruct the surface with color.

**Comment by nmellado** [comment]
Yes, the Point processing toolbox of cgal can be a good way to write complete point-cloud processing pipeline.
I'm closing this issue a your problem seems to be solved.
Please post on Open repository if you need more support.
