### ISSUE TITLE
re problem

### ISSUE THREAD

**Issue by chowchow99** [nmellado/Super4PCS#9]
Hi, thanks your SUPER4PCS packages . It's amazing. I downloaded the newest package from `https://github.com/nmellado/Super4PCS`; 
and sucessfully compiled under the environment WINDOWS 8.1+ Visual Studio 2015+Opencv 3.1+Eigen3.2.8 !  
I clicked the runme.bat at <.\Super4PCS-master\\>  and then checked  the  result.   However,  the result super4pcs.obj file seems not sensible. The two input .obj file can be viewed in an 3D review, while for the result ,the we see nothing on it.
one of the input file.
![image](https://cloud.githubusercontent.com/assets/18543592/14627830/be79d0ac-062a-11e6-8138-d349f50670bb.png)
the result super4pcs.obj  file.
![image](https://cloud.githubusercontent.com/assets/18543592/14627901/5b12ed40-062b-11e6-9421-a42ff74a7274.png)

I think the resolution might mainly related to the below 3 kinds of warnings.Did I miss some important steps so I got the incorrect results?
![image](https://cloud.githubusercontent.com/assets/18543592/14627505/ad2d2f40-0627-11e6-92da-2eda5e6e19f5.png)

**Comment by chowchow99** [comment]
This is the command window.
![image](https://cloud.githubusercontent.com/assets/18543592/14631029/e4745a66-0643-11e6-9a29-661b26241be5.png)

**Comment by nmellado** [comment]
Hi Chowchow99,

Thanks for the feedback.
Can you please send me the output file ?
Can you check Super4PCS have the permissions to create and write the output file ?

Cheers

**Comment by chowchow99** [comment]
Hi ,
Thanks for your attention.
Sorry, attachments in  .obj format are not allowed here, so could I sent the Super4PCS.obj file to you through other ways?
The Super4PCS.obj file were build  after I ran the runme.bat file.  I tried to change the name of the output file as Super4PCS_1.obj , ran the runme.bat file and then  Super4PCS_1.obj  were build in the same directory. 
It seems that there is a class declared to manage reading and writing .obj file .
![image](https://cloud.githubusercontent.com/assets/18543592/14677420/451489d0-0744-11e6-9361-04eac2f99a1b.png)

Is these answer your question?? 
Thanks for your help.

**Comment by nmellado** [comment]
Hi,

Please use the email address indicated in my profile, to send me the obj file.

Cheers

**Comment by chowchow99** [comment]
Hi,
Have had send you through email, please check.

Cheers

**Comment by nmellado** [comment]
Hi,

I've identified the problem : the output .obj file is truncated, the face list is missing.
The aligned points are however correctly saved, and you can open the file with meshlab, you will get something like that : 
![snapshot00](https://cloud.githubusercontent.com/assets/6310221/14701032/49784bec-07a3-11e6-8998-ec86bca33230.png)

I'll push a fix ASAP.

Thanks for the report.

**Comment by chowchow99** [comment]
Hi,
It's good to hear that.
Thanks for your time.
Cheers
